version: "3.9"
services:
  db:
    image: postgres:15
    container_name: fin-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: fin
    ports:
      - "5434:5432"           
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: fin-redis
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:latest
    container_name: fin-localstack
    environment:
      - SERVICES=s3
      - DEBUG=1
    ports:
      - "4566:4566"
    volumes:
      - localstack-data:/var/lib/localstack

volumes:
  pgdata:
  localstack-data: